// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (url, name, description, created_at, last_updated, user_id)
VALUES ($1, $2, $3, NOW(), NOW(), $4)
RETURNING id
`

type CreateFeedParams struct {
	Url         string
	Name        string
	Description string
	UserID      uuid.UUID
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.Url,
		arg.Name,
		arg.Description,
		arg.UserID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteFeed = `-- name: DeleteFeed :one
DELETE FROM feeds
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteFeed(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, deleteFeed, id)
	err := row.Scan(&id)
	return id, err
}

const deleteFeeds = `-- name: DeleteFeeds :exec
DELETE FROM feeds
`

func (q *Queries) DeleteFeeds(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteFeeds)
	return err
}

const getFeedsByName = `-- name: GetFeedsByName :many
SELECT id, url, name, description, created_at, last_updated, user_id FROM feeds WHERE name = $1
`

func (q *Queries) GetFeedsByName(ctx context.Context, name string) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.LastUpdated,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedsByUserId = `-- name: GetFeedsByUserId :many
SELECT id, url, name, description, created_at, last_updated, user_id FROM feeds WHERE user_id = $1
`

func (q *Queries) GetFeedsByUserId(ctx context.Context, userID uuid.UUID) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.LastUpdated,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, url, name, description, created_at, last_updated, user_id FROM feeds WHERE id = $1
`

func (q *Queries) ListFeeds(ctx context.Context, id int32) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.LastUpdated,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedsByURL = `-- name: ListFeedsByURL :many
SELECT id, url, name, description, created_at, last_updated, user_id FROM feeds WHERE url = $1
`

func (q *Queries) ListFeedsByURL(ctx context.Context, url string) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeedsByURL, url)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.LastUpdated,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeed = `-- name: UpdateFeed :one
UPDATE feeds
SET url = $2, name = $3, description = $4, last_updated = NOW()
WHERE id = $1
RETURNING id
`

type UpdateFeedParams struct {
	ID          int32
	Url         string
	Name        string
	Description string
}

func (q *Queries) UpdateFeed(ctx context.Context, arg UpdateFeedParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, updateFeed,
		arg.ID,
		arg.Url,
		arg.Name,
		arg.Description,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
